# ---------------- #
#   Main Configs   #
# ---------------- #
url: ""
baseurl: ""
date_format: "ordinal"
title: FC‘s Blog
subtitle: "Note on Tech & Life"
description: "fangchao的个人博客"
keywords: fangchao
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: FangChao
organization: 
organization_url: 
github_username: alanackart
location: Shanghai, China
email: alanackart@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: HOME

  -
    href: /categories/
    label: CATEGORIES

  -
    href: /archives/
    label: ARCHIVES

  -
    href: /wiki/
    label: WIKI

  -
    href: /links/
    label: LINKS

  -
    href: /about/
    label: ABOUT

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: alanackart/alanackart.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
future: true  
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 6e5bf0a3efafc35f03f1                            #生成的clientID
  clientSecret: 3c0551e9f1d8df7831af2079d6960e3b8033c752    #生成的clientSecret
  repo: alanackart.github.io    #仓库名称
  owner: alanackart    #github用户名
  admin: alanackart  
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-123479765-1
